### ISSUE TITLE
Programming Error while running Docker-compose 

### ISSUE THREAD

**Issue by ParthS007** [Samwalton9/hashtags#14] opened 2019-02-25 16:39 UTC
![screenshot from 2019-02-25 22-07-50](https://user-images.githubusercontent.com/24358501/53352973-d296ba00-3949-11e9-8faa-f95e878cd5b6.png)
![screenshot from 2019-02-25 22-10-36](https://user-images.githubusercontent.com/24358501/53354155-3ae69b00-394c-11e9-9fa4-66c1f96a0f79.png)

@Samwalton9 @Jain-Aditya I am getting this error whenever I run the server. 
Can you please help me with this. Am I missing something?

**Comment by Samwalton9** [comment] 2019-02-25 20:00
Hmm. Can you do `docker ps` and `docker logs hashtags_db_1` and paste the output here?

**Comment by ParthS007** [comment] 2019-02-25 20:20
![screenshot from 2019-02-26 01-45-16](https://user-images.githubusercontent.com/24358501/53366057-bf471700-3968-11e9-99ff-09713e09652b.png)
![screenshot from 2019-02-26 01-46-21](https://user-images.githubusercontent.com/24358501/53366062-c110da80-3968-11e9-87ab-206e41abdf24.png)
![screenshot from 2019-02-26 01-46-47](https://user-images.githubusercontent.com/24358501/53366065-c2da9e00-3968-11e9-8436-fb928fa191c5.png)
![screenshot from 2019-02-26 01-47-38](https://user-images.githubusercontent.com/24358501/53366067-c66e2500-3968-11e9-8d34-2788d6809757.png)

@Samwalton9 Here're the screenshots of above two commands. Thanks for quick reply.

**Comment by Samwalton9** [comment] 2019-02-25 20:59
So the database is up, perhaps migrations didn't run. Can you do `docker logs hashtags_app_1` too? Thanks.

**Comment by ParthS007** [comment] 2019-02-26 16:56
![screenshot from 2019-02-26 22-24-18](https://user-images.githubusercontent.com/24358501/53430866-5bc6f300-3a15-11e9-9710-c0ddfcda077c.png)
@Samwalton9 I think problem exist here.

**Comment by Samwalton9** [comment] 2019-02-26 16:58
Ahh - this is a problem I had on production. It's not clear to me why it happens but sometimes the app container can't resolve the 'db' name to find the database container. The hacky solution to this is to find the IP of the database container (IP address near the bottom of the output of `docker inspect hashtags_db_1`), and then enter that as the database host in `hashtags/settings/base.py` and `scripts/db.py` in place of "db".

**Comment by ParthS007** [comment] 2019-02-26 17:00
okay @Samwalton9 , making the changes :+1:

**Comment by ParthS007** [comment] 2019-02-26 17:09
@Samwalton9 Should It also means that when someone try to run it on development mode(locally), It needs the ip address of that machine or not?
If yes, then I can add Instructions in the Readme for the same so that other devs will not face this problem.

**Comment by Samwalton9** [comment] 2019-02-28 11:09
> Should It also means that when someone try to run it on development mode(locally), It needs the ip address of that machine or not?

Could you explain what you mean by this? I'm not sure I follow.

**Comment by ParthS007** [comment] 2019-02-28 14:52
@Samwalton9  I want to ask that, Is this problem exists for everyone who tries to run it on development mode?

**Comment by Samwalton9** [comment] 2019-02-28 16:01
Ah - you're the only person I've heard having this issue locally. Still, it could be worth documenting, so adding it to the README would be a good idea :)

**Comment by ParthS007** [comment] 2019-02-28 16:29
Okay, I will add it :+1:

**Comment by Samwalton9** [comment] 2019-03-29 15:10
I'm going to close this since the issue is resolved, but a pull request to add an explanation to the README would be welcome!

**Closed by Samwalton9** 2019-03-29 15:10 UTC
